In [ ]:
from utils.read import read_UCR_dataset_name

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('DataSummary.csv')
df = df[df['BakeOff'] == True]

In [3]:
df.head()

,ID,Type,Name,BakeOff,MySelection,Train,Test,Class,Length,ED (w=0),DTW (learned_w),DTW (w=100),Default rate,Data donor/editor
0,1,Image,Adiac,True,2.0,390,391,37,176,0.3887,0.3913 (3),0.3964,0.9591,A. Jalba
1,2,Image,ArrowHead,True,2.0,36,175,3,251,0.2000,0.2000 (0),0.2971,0.6057,L. Ye & E. Keogh
2,3,Spectro,Beef,True,2.0,30,30,5,470,0.3333,0.3333 (0),0.3667,0.8000,K. Kemsley & A. Bagnall
3,4,Image,BeetleFly,True,2.0,20,20,2,512,0.2500,0.3000 (7),0.3000,0.5000,J. Hills & A. Bagnall
4,5,Image,BirdChicken,True,1.0,20,20,2,512,0.4500,0.3000 (6),0.2500,0.5000,J. Hills & A. Bagnall

In [4]:
df = df[df['MySelection'] != 1.0]
df = df[df['MySelection'] != 0.0]
print(len(df))

48

In [31]:
df['Type'].value_counts()

Image        23
Sensor       13
Device        6
Spectro       5
Motion        5
ECG           2
Simulated     1
Name: Type, dtype: int64

In [36]:
df[df['Type'] == 'Motion']

,ID,Type,Name,BakeOff,MySelection,Train,Test,Class,Length,ED (w=0),DTW (learned_w),DTW (w=100),Default rate,Data donor/editor
33,34,Motion,Haptics,True,NaN,155,308,5,1092,0.6299,0.5877 (2),0.6234,0.7825,J. Brady
35,36,Motion,InlineSkate,True,NaN,100,550,7,1882,0.6582,0.6127 (14),0.6164,0.8164,F. Morchen & O. Hoos
71,72,Motion,ToeSegmentation2,True,NaN,36,130,2,343,0.1923,0.0923 (5),0.1615,0.1846,"A. Bagnall, L. Ye & E. Keogh"
82,83,Motion,Worms,True,NaN,181,77,5,900,0.5455,0.4675 (9),0.4156,0.5714,A. Bagnall
83,84,Motion,WormsTwoClass,True,NaN,181,77,2,900,0.3896,0.4156 (7),0.3766,0.4286,A. Bagnall